# Generated by Django 2.2 on 2020-08-15 03:59

import ckeditor.fields
from django.db import migrations, models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dpt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('arbol', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'División político territorial',
                'verbose_name_plural': 'División político territorial',
            },
        ),
        migrations.CreateModel(
            name='Glosary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255, verbose_name='Term')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Term',
                'verbose_name_plural': 'Glosary',
            },
        ),
        migrations.CreateModel(
            name='HistoricalGlosary',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('term', models.CharField(max_length=255, verbose_name='Term')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Term',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSequence',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='name')),
                ('prefix', models.CharField(default='default', max_length=40, verbose_name='Prefix')),
                ('padding', models.PositiveIntegerField(default=4, verbose_name='padding')),
                ('initial', models.PositiveIntegerField(default=1, verbose_name='initial')),
                ('increment', models.PositiveIntegerField(default=1, verbose_name='increment')),
                ('reset', models.PositiveIntegerField(blank=True, null=True, verbose_name='reset')),
                ('last', models.PositiveIntegerField(editable=False, verbose_name='Last')),
                ('next_val', models.PositiveIntegerField(verbose_name='Next')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical sequence',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('prefix', models.CharField(default='default', max_length=40, verbose_name='Prefix')),
                ('padding', models.PositiveIntegerField(default=4, verbose_name='padding')),
                ('initial', models.PositiveIntegerField(default=1, verbose_name='initial')),
                ('increment', models.PositiveIntegerField(default=1, verbose_name='increment')),
                ('reset', models.PositiveIntegerField(blank=True, null=True, verbose_name='reset')),
                ('last', models.PositiveIntegerField(editable=False, verbose_name='Last')),
                ('next_val', models.PositiveIntegerField(verbose_name='Next')),
            ],
            options={
                'verbose_name': 'sequence',
                'verbose_name_plural': 'sequences',
            },
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Sex',
            },
        ),
    ]
